### PR TITLE
Adding kazakh localization file

### PR DESCRIPTION
**Pull request by Arbars**

### CODE REVIEW

**Comment by darkstar** [comment]
Please leave the english strings in as comments, as explained in the header of the file:
````
  *		Also, KEEP the original lines by prefixing them with the
  *		// comment prefix, so that translation context is maintained.
  *		So, for an original line:
  *
  *		  #define STR_2100	"Error"
  *
  *		you would change that into:
  *
  *		  // #define STR_2100	"Error"
  *		  #define STR_2100	"Fout"
````

**Comment by Arbars** [comment]
Damn, I worked with old version of original lang file! Can you cancel a request? I will fix translation and send him. Thanks!

**Comment by waltje** [comment]
Cancelling the PR.  I could have merged it anyways, but thanks for re-doing it ;-)

**Comment by darkstar** [comment]
No need to cancel the request actually... you can just update your branch (either with a second commit that restores those lines, or by re-doing the commit and doing a force-push). In both cases, the PR will be magically updated to reflect your changes :)

**Pull request closed without merging**
